# Basic
title: SWAM 监控系统数据层包文档 
subtitle: SWAN monitor core document
description: 
url: http://nmred.github.io/sf1
author: nmred
email: nmred_2008@126.com
language: zh-CN

# Permalink
root: /
permalink: :category/:title/
tag_dir: tags
archive_dir: archives
category_dir: posts

# Archives
# 2: Paginate result
# 1: Display result in same page
archive: 2
category: 2
tag: 2

# Server
# Hexo uses Connect to serve static files
# Reference: http://www.senchalabs.org/connect/
port: 4000
logger: false
logger_format:

# Date / Time format
# Hexo uses Moment.js to parse and display date
# Reference: http://momentjs.com/docs/#/displaying/format/
date_format: MMM D, YYYY
time_format: H:mm:ss

# Pagination
per_page: 0
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
plugins:
theme: hexo3
exclude_generator:
- category
- tag
- home
- post
- archive

# Enhancement
auto_spacing: false
titlecase: false
highlight:
  enable: true
  line_number: false
  tab_replace: '  '

# Deployment
# Type: github, heroku
# Read documentaion for more information
deploy:
  type: github
  repository: 
  branch: gh-pages
