menu:
  主页: /
  文档: docs/
  仓库: https://github.com/nmred/sf1

doc_sidebar:
  Getting Started:
    Overview: index.html
    Setup: setup.html
    Configuration: configuration.html
    Commands: commands.html
    Migration: migration.html
  Basic Usage:
    Writing: writing.html
    Generating: generating.html
    Tag Plugins: tag-plugins.html
    Server: server.html
    Deployment: deployment.html
  Customization:
    Permalinks: permalinks.html
    Themes: themes.html
    Variables: variables.html
    Pagination: pagination.html
    Helpers: helpers.html
    i18n: i18n.html
  Advanced:
    Models: models.html
    Events: events.html
    Plugins: plugins.html
  Miscellaneous:
    Troubleshooting: troubleshooting.html
    Contributing: contributing.html

