menu:
  主页: /
  文档: docs/
  仓库: https://github.com/nmred/sf1

doc_sidebar:
  安装部署相关:
    RPM 安装包发布: rpm_publish.html
    环境部署: evn_deploy.html
    数据字典: mysql_desc.html
  Inner Api:
    介绍: inner_api.html
    设备管理: device.html
    设备监控器管理: device_monitor.html
    监控器管理: monitor.html
    监控器属性管理: monitor_attr.html
    监控器数据项管理: monitor_metric.html
    监控器 archive 管理: monitor_archive.html
    接口错误代码说明: api_errno.html
  API 开发相关:
    介绍:
    路由规则及设置:
    函数及常用 LIB 的调用:

