menu:
  主页: /
  文档: docs/
  仓库: https://github.com/nmred/sf1

doc_sidebar:
  Inner Api:
    介绍: inner_api.html
    设备管理: device.html
    设备监控器管理: device_monitor.html
    监控器管理: monitor.html
    监控器属性管理: monitor_attr.html

